# Generated by Django 5.0.14 on 2026-01-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Nová'), ('ACCEPTED', 'Přijatá'), ('REJECTED', 'Odmítnutá'), ('COMPLETED', 'Dokončená'), ('TIMEDOUT', 'Propáslá')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
